name: flutter_eval
description: Flutter bridge library for dart_eval, enabling creation of fully dynamic Flutter apps and widgets that can be loaded from a file or the Internet at runtime.
version: 0.8.1
homepage: https://github.com/ethanblake4/flutter_eval

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - flutter
  - codepush
  - interpreter
  - dynamic
  - widget

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dart_eval: ^0.8.1
  path_provider: ^2.1.0
  http: ^1.1.0

dev_dependencies:
  build_runner: any
  flutter_test:
    sdk: flutter
  flutter_lints: '>=6.0.0'
    
flutter:
